-- UlasJujur
-- Static keyword dictionary for Golang Lapis 2 aggregation.
-- No sentiment/emotion logic is stored here.

DROP TABLE IF EXISTS issue_keywords;

CREATE TABLE issue_keywords (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    UNIQUE KEY uq_issue_keyword (keyword),
    INDEX idx_issue_category (category)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

INSERT INTO issue_keywords (category, keyword) VALUES

-- =========================================================
-- PENGIRIMAN
-- =========================================================
('Pengiriman', 'lelet'),
('Pengiriman', 'lama'),
('Pengiriman', 'telat'),
('Pengiriman', 'lambat'),
('Pengiriman', 'nyasar'),
('Pengiriman', 'belum sampai'),
('Pengiriman', 'belom sampai'),
('Pengiriman', 'kurir lama'),
('Pengiriman', 'pengiriman lama'),
('Pengiriman', 'pengiriman telat'),
('Pengiriman', 'kirim lama'),
('Pengiriman', 'kirimnya lama'),
('Pengiriman', 'lama nyampe'),
('Pengiriman', 'lama sampai'),
('Pengiriman', 'ga nyampe'),
('Pengiriman', 'gak nyampe'),
('Pengiriman', 'gk nyampe'),
('Pengiriman', 'nggak nyampe'),
('Pengiriman', 'belum nyampe'),
('Pengiriman', 'belom nyampe'),
('Pengiriman', 'ngaret'),
('Pengiriman', 'molor'),
('Pengiriman', 'lemot'),
('Pengiriman', 'kurir lelet'),
('Pengiriman', 'kurir telat'),
('Pengiriman', 'salah alamat'),
('Pengiriman', 'salah kirim'),
('Pengiriman', 'paket nyasar'),
('Pengiriman', 'estimasi lewat'),
('Pengiriman', 'lebih lama'),
('Pengiriman', 'nunggu lama'),

-- =========================================================
-- KEMASAN
-- =========================================================
('Kemasan', 'penyok'),
('Kemasan', 'robek'),
('Kemasan', 'sobek'),
('Kemasan', 'basah'),
('Kemasan', 'bocor'),
('Kemasan', 'hancur'),
('Kemasan', 'remuk'),
('Kemasan', 'gepeng'),
('Kemasan', 'packing rusak'),
('Kemasan', 'kemasan rusak'),
('Kemasan', 'kardus rusak'),
('Kemasan', 'dus rusak'),
('Kemasan', 'packing jelek'),
('Kemasan', 'kemasan jelek'),
('Kemasan', 'packing asal'),
('Kemasan', 'packing berantakan'),
('Kemasan', 'packing kurang aman'),
('Kemasan', 'kemasan kurang aman'),
('Kemasan', 'bubble wrap tipis'),
('Kemasan', 'bubble wrap kurang'),
('Kemasan', 'ga ada bubble wrap'),
('Kemasan', 'gak ada bubble wrap'),
('Kemasan', 'segel rusak'),
('Kemasan', 'segel terbuka'),
('Kemasan', 'segel lepas'),
('Kemasan', 'kardus penyok'),
('Kemasan', 'dus penyok'),
('Kemasan', 'kotak penyok'),
('Kemasan', 'bungkus rusak'),
('Kemasan', 'bungkus robek'),

-- =========================================================
-- KUALITAS
-- =========================================================
('Kualitas', 'rusak'),
('Kualitas', 'cacat'),
('Kualitas', 'jelek'),
('Kualitas', 'zonk'),
('Kualitas', 'ampas'),
('Kualitas', 'pecah'),
('Kualitas', 'retak'),
('Kualitas', 'baret'),
('Kualitas', 'buruk'),
('Kualitas', 'defect'),
('Kualitas', 'gak berfungsi'),
('Kualitas', 'ga berfungsi'),
('Kualitas', 'gk berfungsi'),
('Kualitas', 'nggak berfungsi'),
('Kualitas', 'tidak berfungsi'),
('Kualitas', 'mati'),
('Kualitas', 'error'),
('Kualitas', 'bermasalah'),
('Kualitas', 'cepat rusak'),
('Kualitas', 'cepet rusak'),
('Kualitas', 'ga awet'),
('Kualitas', 'gak awet'),
('Kualitas', 'gk awet'),
('Kualitas', 'nggak awet'),
('Kualitas', 'rapuh'),
('Kualitas', 'ringkih'),
('Kualitas', 'kualitas buruk'),
('Kualitas', 'kualitas jelek'),
('Kualitas', 'kualitas rendah'),
('Kualitas', 'tidak tahan lama'),
('Kualitas', 'gampang rusak'),
('Kualitas', 'mudah rusak'),
('Kualitas', 'gagal fungsi'),

-- =========================================================
-- HARGA
-- =========================================================
('Harga', 'mahal'),
('Harga', 'kemahalan'),
('Harga', 'overprice'),
('Harga', 'overpriced'),
('Harga', 'pricey'),
('Harga', 'boncos'),
('Harga', 'ga worth it'),
('Harga', 'gak worth it'),
('Harga', 'gk worth it'),
('Harga', 'nggak worth it'),
('Harga', 'tidak worth it'),
('Harga', 'kurang worth it'),
('Harga', 'ga sebanding'),
('Harga', 'gak sebanding'),
('Harga', 'gk sebanding'),
('Harga', 'tidak sebanding'),
('Harga', 'harga tinggi'),
('Harga', 'terlalu mahal'),
('Harga', 'mahal banget'),
('Harga', 'mahal bgt'),
('Harga', 'harga kemahalan'),
('Harga', 'harga ga masuk akal'),
('Harga', 'harga gak masuk akal'),
('Harga', 'harga tidak masuk akal'),
('Harga', 'kemahalan banget'),
('Harga', 'uang sia sia'),

-- =========================================================
-- PELAYANAN
-- =========================================================
('Pelayanan', 'jutek'),
('Pelayanan', 'cuek'),
('Pelayanan', 'slow respon'),
('Pelayanan', 'slowres'),
('Pelayanan', 'slow response'),
('Pelayanan', 'respon lama'),
('Pelayanan', 'respon lambat'),
('Pelayanan', 'lama respon'),
('Pelayanan', 'ga respon'),
('Pelayanan', 'gak respon'),
('Pelayanan', 'gk respon'),
('Pelayanan', 'nggak respon'),
('Pelayanan', 'tidak respon'),
('Pelayanan', 'ga dibales'),
('Pelayanan', 'gak dibales'),
('Pelayanan', 'gk dibales'),
('Pelayanan', 'nggak dibales'),
('Pelayanan', 'tidak dibalas'),
('Pelayanan', 'susah dihubungi'),
('Pelayanan', 'sulit dihubungi'),
('Pelayanan', 'diabaikan'),
('Pelayanan', 'ga membantu'),
('Pelayanan', 'gak membantu'),
('Pelayanan', 'gk membantu'),
('Pelayanan', 'nggak membantu'),
('Pelayanan', 'tidak membantu'),
('Pelayanan', 'tidak ramah'),
('Pelayanan', 'ga ramah'),
('Pelayanan', 'gak ramah'),
('Pelayanan', 'seller cuek'),
('Pelayanan', 'admin cuek'),
('Pelayanan', 'admin jutek'),
('Pelayanan', 'seller jutek'),
('Pelayanan', 'pelayanan buruk'),
('Pelayanan', 'pelayanan jelek'),
('Pelayanan', 'bad service'),
('Pelayanan', 'ribet'),
('Pelayanan', 'ngeribetin'),
('Pelayanan', 'dipersulit'),
('Pelayanan', 'komplain lama'),
('Pelayanan', 'komplain ga ditanggapi'),
('Pelayanan', 'komplain gak ditanggapi');
